INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (18, 18, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (19, 19, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (16, 18, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (17, 18, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (7, 15, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (8, 15, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (9, 15, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (10, 16, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (11, 16, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (12, 16, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (13, 17, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (14, 17, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (15, 17, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (20, 19, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (21, 19, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (22, 20, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (23, 20, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (24, 20, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (25, 21, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (26, 21, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (27, 21, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (28, 22, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (29, 22, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (30, 22, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (31, 23, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (32, 23, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (33, 23, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (34, 24, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (35, 24, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (36, 24, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (37, 25, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (38, 25, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (39, 25, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (40, 26, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (41, 26, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (42, 26, 'Не могу', '', 1);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (43, 27, 'Могу и всегда так поступаю', '', 6);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (44, 27, 'Могу, но не всегда так поступаю', '', 2);
INSERT INTO `modx_usertest_answers` (`id`, `question_id`, `answer`, `answer_img`, `point`) VALUES (45, 27, 'Не могу', '', 1);
